### ISSUE TITLE
Link to kodus/server-log

### ISSUE THREAD

**Issue by mindplay-dk** [s992/chromelogger-cf#3]
Hi,

The original Chrome Logger extension isn't being updated - the maintainer ignore pull-requests and has been unresponsive on all channels.

I'm not sure if you're still maintaining this library? But I've published [an alternative Chrome extension](https://github.com/kodus/server-log) that adds a dedicated "Server Log" panel.

Would you please consider adding a link?

You also might consider adding support for the `X-ServerLog-Location` header, which enables you to break the header-size limitations (in Chrome, Apache, NGINX, etc.) and remove the cap on log size.

Thanks,
  Rasmus

**Comment by s992** [comment]
@mindplay-dk I haven't maintained or used this in quite a while, but I'm happy to add a link. Does `server-log` use the same API as ChromeLogger?

Can you elaborate on what would be involved in adding support for `X-ServerLog-Location`?

**Comment by mindplay-dk** [comment]
> Does server-log use the same API as ChromeLogger?

It is backwards compatible with the `X-ChromeLogger-Data` header - is that what you meant by API?

> Can you elaborate on what would be involved in adding support for X-ServerLog-Location?

Simply emit the same JSON data (which you would normally base64 encode and pack into a header) to a temporary, web-accessible file instead - and emit an `X-ServerLog-Location` header with a (relative or absolute) URL of the JSON file.

You can see the changes I implemented in our PHP library to support it [here](https://github.com/kodus/chrome-logger/pull/4/files).

**Comment by s992** [comment]
I can definitely add a link to `server-log` the README, but I don't have time to build out support for `X-ServerLog-Location`. Would be happy to review a PR making that change, though. :)

**Comment by mindplay-dk** [comment]
That's fine :-)

The extension works as a drop-in replacement for the ChromeLogger extension - if you're fine with the header-size limitations, you can use this extension just to get your server-log on a separate panel instead of mixed-in with your client-side log.

Everything else is optional :-)
